language: python

python:
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - pip install dash folium nltk dash_daq pytest pandas geojson
  - pip install dash_bootstrap_components

script:
# FIXME: Get all tests to work
#  - cd ADUniverse; ls -l test_*.py; pytest test_*.py
#  - cd ADUniverse; pytest test_update_map.py
 - cd ADUniverse; ls -l test_*.py; pytest test_financials.py
