language: python

python:
  - "3.6"

install:
  - sudo apt-get update  # get most recent installer for linux
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh # downloading miniconda
  - bash miniconda.sh -b -p $HOME/miniconda   # install miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"   # setup miniconda to the path 
  - hash -r      # ?
  - conda config --set always_yes yes --set changeps1 no  # config conda
  - conda update --quiet conda    # kill message
  - conda info --all       # yield info
  
#   - conda install pip
#   - pip install dash folium nltk dash_daq pytest pandas geojson  # conda version of pip
#   - pip install dash_bootstrap_components    # 
  
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - source activate test-environment
#   - conda install pip
#   - pip install -r requirements.txt
  - conda install -f -y -q --name test-environment -c conda-forge --file requirements.txt

  
#     Install support for large files
  - sudo apt-get install curl
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - git lfs install
  
script:
#  - cd ADUniverse; ls -l test_*.py; pytest test_*.py
 - ls -l ADUniverse/test_*.py; pytest ADUniverse/test_*.py
