language: python

python:
  - "3.6"

install:
  - sudo apt-get update  # get most recent installer for linux
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh # downloading miniconda
  - bash miniconda.sh -b -p $HOME/miniconda   # install miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"   # setup miniconda to the path 
  - hash -r      # ?
  - conda config --set always_yes yes --set changeps1 no  # config conda
  - conda update --quiet conda    # kill message
  - conda info --all       # yield info
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - source activate test-environment
#   - conda install pip
#   - pip install -r requirements.txt
  - conda install -f -y -q --name test-environment -c conda-forge --file requirements.txt
  - pip install dash-dangerously-set-inner-html
#   - conda install -c conda-forge git-lfs 
  - git lfs install

  
#     Niu thinks we don't need LFS if we just try to run it in the terminal without push anything back to git repo
  
script:
 - cd ADUniverse; ls -l test_*.py; pytest test_*.py
