# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            'ADUniverse'
tagline:          'This Is It.'
description:      'Creating a tool to support homeowners interested in building an ADU' 
url:              "https://uwescience.github.io"
baseurl:          "/ADUniverse"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/ADUniverse
