# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG: ADUniverse
tagline:          ''
description:      'A 2019 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/ADUniverse"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/ADUniverse
